// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgpqBu_7zUIS5hZJ8Fm9XkniG-lBATamc',
    appId: '1:313115989825:web:cc9a254af65e03efef73c0',
    messagingSenderId: '313115989825',
    projectId: 'demofire-b0e2d',
    authDomain: 'demofire-b0e2d.firebaseapp.com',
    storageBucket: 'demofire-b0e2d.appspot.com',
    measurementId: 'G-KG83QGZK8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1NjzSTNsLTcb9cObaAIVPzJFWmpr9AkA',
    appId: '1:313115989825:android:f4de3cb8144da462ef73c0',
    messagingSenderId: '313115989825',
    projectId: 'demofire-b0e2d',
    storageBucket: 'demofire-b0e2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqN9Qt3OOFLlDeyO8V8MsKJQH9ZWr6KBU',
    appId: '1:313115989825:ios:d147fb234201711fef73c0',
    messagingSenderId: '313115989825',
    projectId: 'demofire-b0e2d',
    storageBucket: 'demofire-b0e2d.appspot.com',
    androidClientId: '313115989825-0bn1eals4b3jq56u07nq951iodahstte.apps.googleusercontent.com',
    iosClientId: '313115989825-qfkrr7dkki7dc3dvggqlltrkoeou3d61.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoChatFirebase',
  );
}
